name: Deploy to shinyapps.io
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rsconnect
          needs: check

      - name: Deploy
        env:
          SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
          SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
          SHINY_USER: ${{ secrets.SHINY_USER }}
        run: |
          Rscript --vanilla app/deploy.R
